apiVersion: batch/v1
kind: CronJob
metadata:
  name: drive-backup
spec:
  schedule: "*/1 * * * *" 
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: drive-backup
            image: niranjanmayur/drive_oauth
            volumeMounts:
            - name: shared-volume
              mountPath: /app/assignment  # Mount path within the container
            workingDir: /app
          volumes:
          - name: shared-volume
            hostPath:
              path: /Users/niranjanmayur/Desktop/sem 6/CC/CCProject/assignment  # Path to the shared folder in your laptop
          restartPolicy: OnFailure
